# Generated by Django 2.2.6 on 2020-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detailPageName', models.CharField(max_length=200)),
                ('portID', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('typology', models.IntegerField()),
                ('activityLevel', models.CharField(max_length=200)),
                ('collectionType', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('pricelevel', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('mealInfo', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(max_length=200)),
                ('longDescription', models.TextField()),
                ('externalContent', models.CharField(max_length=10)),
                ('minimumAge', models.CharField(blank=True, max_length=10)),
                ('wheelChairAccessible', models.CharField(max_length=10)),
                ('featured', models.CharField(max_length=10)),
            ],
        ),
    ]
