# Generated by Django 2.2.6 on 2020-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXapps', '0002_auto_20200404_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='externalContent',
            field=models.BooleanField(default=True),
        ),
    ]
