# Generated by Django 2.2.6 on 2020-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXapps', '0003_auto_20200405_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='collectionType',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='mealInfo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='portID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
