# Generated by Django 2.2.6 on 2020-04-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXapps', '0004_auto_20200409_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='typology',
            field=models.CharField(max_length=20),
        ),
    ]
