# Generated by Django 2.2.6 on 2020-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXapps', '0005_auto_20200409_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='activityLevel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
