# Generated by Django 2.2.6 on 2020-04-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXapps', '0006_auto_20200409_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='collectionType',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
