# Generated by Django 2.2.6 on 2020-04-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXapps', '0008_auto_20200422_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidata',
            old_name='priceLevel',
            new_name='pricelevel',
        ),
    ]
